name: CI-Harbor

on:
  push:
    branches:
      - main  # 또는 배포할 브랜치

jobs:
  build-and-push:
    runs-on: self-hosted  # Self-hosted runner 사용
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build frontend
        working-directory: ./frontend # next.js 프로젝트 경로
        run: |
          npm install
          npm run build

      - name: Login to Harbor
        run: |
          docker login https://192.168.2.76:443 -u cicd_sa -p ${{ secrets.HARBOR_PASSWORD }}


      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.HARBOR_URL }}/hama/hama_frontend:latest ./frontend
          docker push ${{ secrets.HARBOR_URL }}/hama/hama_frontend:latest
